name: speedonet_tech
description: Speedonet Technician App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # HTTP
  dio: ^5.4.0

  # Local storage
  shared_preferences: ^2.2.2

  # UI
  google_fonts: ^6.2.1
  intl: ^0.19.0

flutter:
  uses-material-design: true
